version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: final-project
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
    - postgres
    environment:
      NODE_ENV: development
      SERVER_PORT: 8000
      ACCESS_TOKEN_SECRET: 'access_token_secret'
      REFRESH_TOKEN_SECRET: 'refresh_token_secret'
      DB_CLIENT: 'pg'
      DB_NAME: 'realestate'
      DB_HOST: 'postgres'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_PORT: '5432'
    

  postgres:
    image: postgres:16.1
    container_name: final_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realestate